version: "3.4"

services:

  db:
    image: mysql:5.7
    ports:
      - "3376:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: quackersdb
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - qoshop-dbdata:/var/lib/mysql
    networks:
      - qoshop-net

volumes:
  qoshop-dbdata:

networks:
  qoshop-net:

