version: "3.4"

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: quackersdb
      MYSQL_USER: quackers
      MYSQL_PASSWORD: quackers
    volumes:
      - qoshop-dbdata:/var/lib/mysql
    networks:
      - qoshop-net

volumes:
  qoshop-dbdata:

networks:
  qoshop-net:

